### ISSUE TITLE
Migrar a libomegaup para un desarrollo mas sencillo de la CLI

### ISSUE THREAD

**Issue by lhchavez** [Apocryphon-X/omegaup-cli#9]
Tenemos un paquete en pypi https://pypi.org/project/omegaup/1.2.0/ y podemos autogenerarlo cada que cambia el API. eso disminuiría el costo de desarrollar el CLI y además tiene anotaciones de tipos con [mypy](https://mypy.readthedocs.io/en/stable/).

El API está en https://github.com/omegaup/libomegaup/blob/main/omegaup/api.py, la documentación en https://github.com/omegaup/libomegaup/tree/main/docs (necesito ver cómo desplegarlo usando GitHub Pages) y tenemos un ejemplo de uso en https://github.com/ComiteMexicanoDeInformatica/omegaUp-deploy/blob/a3982cfacb6476c528cea8177c772ce460e06c60/upload.py#L264

(y también ya se le agregó el soporte de usar el API token).

**Comment by Apocryphon-X** [comment]
Me parece buena idea! No parece que el cambio sea tan grande en cuestión de código, así que debe ser relativamente sencillo modificar la CLI para que se incorpore con la libomegaup. (Que el paquete este en pypi, tenga documentaciones y ademas sea autogenerado facilita mucho las cosas)

**Comment by Apocryphon-X** [comment]
Muchas gracias por la sugerencia :)
